DROP TABLE x_admins               ;
DROP TABLE x_admin_emails         ;
DROP TABLE x_collections          ;
DROP TABLE x_coll_parameters      ;
DROP TABLE x_page_lists           ;
DROP TABLE x_page_list_definitions;
DROP TABLE x_reports              ;
DROP TABLE x_report_shr_prms      ;
DROP TABLE x_event_parameters     ;
DROP TABLE x_event_parameter_values;
